'use client';

import { useState } from 'react';
import { 
  Clock,
  Package,
  Bell,
  Target,
  TrendingUp,
  Zap,
  RefreshCw,
  Save,
  AlertCircle,
  CheckCircle,
  BarChart3,
  Settings as SettingsIcon,
  Calendar,
  Filter
} from 'lucide-react';

export default function SystemConfiguration({ 
  onRefresh,
  isLoading = false,
  userRole = 'manager'
}) {
  const [activeTab, setActiveTab] = useState('workflow');
  const [isSaving, setIsSaving] = useState(false);
  const [saveMessage, setSaveMessage] = useState(null);
  
  // System workflow configuration data
  const [configData, setConfigData] = useState({
    // Order Workflow
    autoAssignOrders: true,
    orderPriorityRules: 'time_based',
    maxOrdersPerWaiter: 6,
    kitchenAlertDelay: 10,
    readyToServeBuffer: 5,
    
    // Table Management
    tableAutoAssign: true,
    minTableTurnaround: 15,
    reservationHoldTime: 15,
    walkInPriority: 'fifo',
    maxPartySize: 8,
    
    // Inventory Automation
    autoLowStockAlert: true,
    lowStockThreshold: 20,
    autoReorderEnabled: false,
    expiryNotifications: true,
    wasteTrackingEnabled: true,
    
    // Performance Metrics
    dailySalesTarget: 5000,
    customerSatisfactionTarget: 90,
    tableTurnoverTarget: 2.5,
    wastePercentageTarget: 5,
    staffEfficiencyTarget: 85,
    
    // Automation Rules
    autoCancelUnconfirmed: true,
    cancelAfterHours: 2,
    autoApplyDiscounts: false,
    bulkOrderDiscount: 5,
    repeatCustomerBonus: 3,
    
    // Alert & Notification Rules
    notifyOnLowStock: true,
    notifyOnHighWaste: true,
    notifyOnSlowService: true,
    peakHourAlerts: true,
    staffPerformanceAlerts: true,
    
    // Reporting Automation
    autoGenerateDailyReport: true,
    dailyReportTime: '23:30',
    weeklyReportDay: 'monday',
    monthlyReportDay: 1,
    autoEmailReports: false
  });

  const tabs = [
    { id: 'workflow', label: 'Workflow Rules', icon: SettingsIcon },
    { id: 'automation', label: 'Automation', icon: Zap },
    { id: 'alerts', label: 'Alert Rules', icon: Bell },
    { id: 'metrics', label: 'Performance Metrics', icon: Target },
    { id: 'reporting', label: 'Reporting', icon: BarChart3 }
  ];

  const handleToggle = (field) => {
    setConfigData(prev => ({
      ...prev,
      [field]: !prev[field]
    }));
  };

  const handleNumberChange = (field, value) => {
    setConfigData(prev => ({
      ...prev,
      [field]: parseInt(value) || 0
    }));
  };

  const handleSelectChange = (field, value) => {
    setConfigData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSave = async () => {
    setIsSaving(true);
    setSaveMessage(null);
    
    try {
      // Simulate API save
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      console.log('Saving system configuration:', configData);
      
      setSaveMessage({
        type: 'success',
        text: 'System configuration saved successfully!'
      });
      
    } catch (error) {
      setSaveMessage({
        type: 'error',
        text: 'Failed to save configuration'
      });
    } finally {
      setIsSaving(false);
      setTimeout(() => setSaveMessage(null), 3000);
    }
  };

  const handleReset = () => {
    setConfigData({
      autoAssignOrders: true,
      orderPriorityRules: 'time_based',
      maxOrdersPerWaiter: 6,
      kitchenAlertDelay: 10,
      readyToServeBuffer: 5,
      tableAutoAssign: true,
      minTableTurnaround: 15,
      reservationHoldTime: 15,
      walkInPriority: 'fifo',
      maxPartySize: 8,
      autoLowStockAlert: true,
      lowStockThreshold: 20,
      autoReorderEnabled: false,
      expiryNotifications: true,
      wasteTrackingEnabled: true,
      dailySalesTarget: 5000,
      customerSatisfactionTarget: 90,
      tableTurnoverTarget: 2.5,
      wastePercentageTarget: 5,
      staffEfficiencyTarget: 85,
      autoCancelUnconfirmed: true,
      cancelAfterHours: 2,
      autoApplyDiscounts: false,
      bulkOrderDiscount: 5,
      repeatCustomerBonus: 3,
      notifyOnLowStock: true,
      notifyOnHighWaste: true,
      notifyOnSlowService: true,
      peakHourAlerts: true,
      staffPerformanceAlerts: true,
      autoGenerateDailyReport: true,
      dailyReportTime: '23:30',
      weeklyReportDay: 'monday',
      monthlyReportDay: 1,
      autoEmailReports: false
    });
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case 'workflow':
        return (
          <div className="space-y-6">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <SettingsIcon className="w-5 h-5 mr-2" />
                Order Processing Workflow
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto-assign Orders to Staff</p>
                    <p className="text-sm text-gray-600">Automatically assign new orders to available staff</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.autoAssignOrders}
                      onChange={() => handleToggle('autoAssignOrders')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Order Priority Rules
                  </label>
                  <select
                    value={configData.orderPriorityRules}
                    onChange={(e) => handleSelectChange('orderPriorityRules', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="time_based">Time-based (FIFO)</option>
                    <option value="complexity_based">Complexity-based</option>
                    <option value="station_based">Kitchen Station-based</option>
                    <option value="manual">Manual Assignment</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Maximum Orders per Waiter
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="10"
                    value={configData.maxOrdersPerWaiter}
                    onChange={(e) => handleNumberChange('maxOrdersPerWaiter', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                  <p className="text-sm text-gray-500 mt-1">Prevents staff overload during peak hours</p>
                </div>
              </div>
            </div>
            
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Clock className="w-5 h-5 mr-2" />
                Table Management Rules
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto-assign Tables</p>
                    <p className="text-sm text-gray-600">Automatically assign available tables to waiting customers</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.tableAutoAssign}
                      onChange={() => handleToggle('tableAutoAssign')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Minimum Table Turnaround Time (minutes)
                  </label>
                  <input
                    type="number"
                    min="5"
                    max="60"
                    value={configData.minTableTurnaround}
                    onChange={(e) => handleNumberChange('minTableTurnaround', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Maximum Party Size
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="20"
                    value={configData.maxPartySize}
                    onChange={(e) => handleNumberChange('maxPartySize', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
              </div>
            </div>
          </div>
        );
        
      case 'automation':
        return (
          <div className="space-y-6">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Zap className="w-5 h-5 mr-2" />
                Business Automation
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto-cancel Unconfirmed Reservations</p>
                    <p className="text-sm text-gray-600">Cancel reservations not confirmed within specified time</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.autoCancelUnconfirmed}
                      onChange={() => handleToggle('autoCancelUnconfirmed')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                {configData.autoCancelUnconfirmed && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Cancel After (hours)
                    </label>
                    <input
                      type="number"
                      min="1"
                      max="24"
                      value={configData.cancelAfterHours}
                      onChange={(e) => handleNumberChange('cancelAfterHours', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                    />
                  </div>
                )}
                
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto-apply Bulk Order Discount</p>
                    <p className="text-sm text-gray-600">Apply discount automatically for large orders</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.autoApplyDiscounts}
                      onChange={() => handleToggle('autoApplyDiscounts')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                {configData.autoApplyDiscounts && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Bulk Order Discount (%)
                    </label>
                    <input
                      type="number"
                      min="1"
                      max="50"
                      value={configData.bulkOrderDiscount}
                      onChange={(e) => handleNumberChange('bulkOrderDiscount', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                    />
                  </div>
                )}
              </div>
            </div>
            
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Package className="w-5 h-5 mr-2" />
                Inventory Automation
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto Low Stock Alerts</p>
                    <p className="text-sm text-gray-600">Send alerts when inventory reaches low levels</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.autoLowStockAlert}
                      onChange={() => handleToggle('autoLowStockAlert')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                {configData.autoLowStockAlert && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Low Stock Threshold
                    </label>
                    <input
                      type="number"
                      min="1"
                      max="100"
                      value={configData.lowStockThreshold}
                      onChange={(e) => handleNumberChange('lowStockThreshold', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                    />
                    <p className="text-sm text-gray-500 mt-1">Alert when quantity falls below this level</p>
                  </div>
                )}
                
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Expiry Date Notifications</p>
                    <p className="text-sm text-gray-600">Notify staff when items are nearing expiry</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.expiryNotifications}
                      onChange={() => handleToggle('expiryNotifications')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
              </div>
            </div>
          </div>
        );
        
      case 'alerts':
        return (
          <div className="space-y-6">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Bell className="w-5 h-5 mr-2" />
                Alert Configuration
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Low Stock Alerts</p>
                    <p className="text-sm text-gray-600">Receive notifications when inventory is low</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.notifyOnLowStock}
                      onChange={() => handleToggle('notifyOnLowStock')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">High Waste Alerts</p>
                    <p className="text-sm text-gray-600">Alert when waste percentage exceeds target</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.notifyOnHighWaste}
                      onChange={() => handleToggle('notifyOnHighWaste')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Slow Service Alerts</p>
                    <p className="text-sm text-gray-600">Notify when order preparation time exceeds limit</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.notifyOnSlowService}
                      onChange={() => handleToggle('notifyOnSlowService')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Peak Hour Alerts</p>
                    <p className="text-sm text-gray-600">Notifications during high traffic periods</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.peakHourAlerts}
                      onChange={() => handleToggle('peakHourAlerts')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
              </div>
            </div>
          </div>
        );
        
      case 'metrics':
        return (
          <div className="space-y-6">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Target className="w-5 h-5 mr-2" />
                Performance Targets
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Daily Sales Target (ETB)
                  </label>
                  <input
                    type="number"
                    min="0"
                    value={configData.dailySalesTarget}
                    onChange={(e) => handleNumberChange('dailySalesTarget', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Customer Satisfaction Target (%)
                  </label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={configData.customerSatisfactionTarget}
                    onChange={(e) => handleNumberChange('customerSatisfactionTarget', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Table Turnover Target
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.1"
                    value={configData.tableTurnoverTarget}
                    onChange={(e) => handleNumberChange('tableTurnoverTarget', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Waste Percentage Target (%)
                  </label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={configData.wastePercentageTarget}
                    onChange={(e) => handleNumberChange('wastePercentageTarget', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
              </div>
            </div>
          </div>
        );
        
      case 'reporting':
        return (
          <div className="space-y-6">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <BarChart3 className="w-5 h-5 mr-2" />
                Automated Reporting
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-gray-900">Auto-generate Daily Reports</p>
                    <p className="text-sm text-gray-600">Generate end-of-day reports automatically</p>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={configData.autoGenerateDailyReport}
                      onChange={() => handleToggle('autoGenerateDailyReport')}
                      className="sr-only peer"
                    />
                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-purple-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                  </label>
                </div>
                
                {configData.autoGenerateDailyReport && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Daily Report Time
                    </label>
                    <input
                      type="time"
                      value={configData.dailyReportTime}
                      onChange={(e) => handleSelectChange('dailyReportTime', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                    />
                  </div>
                )}
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Weekly Report Day
                  </label>
                  <select
                    value={configData.weeklyReportDay}
                    onChange={(e) => handleSelectChange('weeklyReportDay', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="monday">Monday</option>
                    <option value="tuesday">Tuesday</option>
                    <option value="wednesday">Wednesday</option>
                    <option value="thursday">Thursday</option>
                    <option value="friday">Friday</option>
                    <option value="saturday">Saturday</option>
                    <option value="sunday">Sunday</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Monthly Report Day
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="28"
                    value={configData.monthlyReportDay}
                    onChange={(e) => handleNumberChange('monthlyReportDay', e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                  />
                </div>
              </div>
            </div>
          </div>
        );
        
      default:
        return null;
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-lg p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">System Configuration</h2>
          <p className="text-gray-600 mt-1">Configure workflow rules, automation, and system behavior</p>
        </div>
        <div className="flex items-center space-x-3 mt-4 sm:mt-0">
          <button
            onClick={handleReset}
            className="flex items-center justify-center space-x-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl font-medium transition"
          >
            <RefreshCw className="w-4 h-4" />
            <span>Reset Defaults</span>
          </button>
          <button
            onClick={handleSave}
            disabled={isSaving}
            className="flex items-center justify-center space-x-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl font-semibold transition disabled:opacity-50"
          >
            {isSaving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Saving...</span>
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                <span>Save Changes</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Save Message */}
      {saveMessage && (
        <div className={`mb-6 p-4 rounded-xl ${
          saveMessage.type === 'success' 
            ? 'bg-green-50 border border-green-200' 
            : 'bg-red-50 border border-red-200'
        }`}>
          <div className="flex items-center">
            {saveMessage.type === 'success' ? (
              <CheckCircle className="w-5 h-5 text-green-600 mr-3" />
            ) : (
              <AlertCircle className="w-5 h-5 text-red-600 mr-3" />
            )}
            <p className={`font-medium ${
              saveMessage.type === 'success' ? 'text-green-800' : 'text-red-800'
            }`}>
              {saveMessage.text}
            </p>
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="mb-6">
        <div className="flex flex-wrap border-b border-gray-200">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center px-4 py-3 border-b-2 font-medium text-sm transition ${
                  isActive
                    ? 'border-purple-600 text-purple-600 bg-purple-50'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                <Icon className="w-4 h-4 mr-2" />
                {tab.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab Content */}
      <div className="min-h-[400px]">
        {renderTabContent()}
      </div>

      {/* Info Box */}
      <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-xl">
        <div className="flex items-start">
          <AlertCircle className="w-5 h-5 text-blue-600 mr-3 mt-0.5" />
          <div>
            <p className="text-sm text-blue-800">
              <span className="font-semibold">Note:</span> These settings control how the system operates automatically. 
              Changes will affect workflows, alerts, and automated processes.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}